version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA:-public}
      POSTGRES_DATABASE_NAME: ${POSTGRES_DATABASE_NAME:-dockerdb}
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin:/var/lib/pgadmin
      - ./pgpass:/pgpass

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
    logging:
      driver: "none"

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: